version: "3.4"

# map raw data folder on local host machine to existing directory in container
x-ceph-volume:
  &ceph-volume
  type: bind
  source: /Users/joseph/SSHFS/aeon/ceph/aeon
  target: /ceph/aeon

# map shared folder on local host machine to $HOME/djstore in container
x-djstore-volume:
  &djstore-volume
  type: bind
  source: /Users/joseph/datajoint/projects/Aeon/mnt/djstore
  target: /home/anaconda/djstore

# common options that are shared among different services
x-aeon-ingest-common:
  &aeon-ingest-common
  platform: linux/amd64
  build:
    context: ./
    args:
      - GITHUB_USER=vathes
      - GITHUB_REPO=aeon_mecha
      - GITHUB_BRANCH=datajoint_pipeline
      - SSH_KEY
  # user: 801150979:anaconda
  extra_hosts:
    - "host.docker.internal:host-gateway" # 172.17.0.1
  env_file: .env
  volumes:
    - *djstore-volume
    - *ceph-volume

# instead of printing the help doc multiple times change the command to something like:
#  ["conda", "run", "-n", "aeon_env", "aeon_ingest", "high", "-d", "60", "-s", "1", "-m", "-1"]
services:
  aeon_high:
    *aeon-ingest-common
    command: ["conda", "run", "-n", "aeon_env", "aeon_ingest", "--help"]
  aeon_mid:
    *aeon-ingest-common
    command: ["conda", "run", "-n", "aeon_env", "aeon_ingest", "--help"]
  aeon_low:
    *aeon-ingest-common
    command: ["conda", "run", "-n", "aeon_env", "aeon_ingest", "--help"]
