# sudo docker-compose -p aeon_dev -f ./aeon/dj_pipeline/docker/image/docker-compose-dev.yml up --build -d
# sudo docker-compose -p aeon_dev -f ./aeon/dj_pipeline/docker/image/docker-compose-dev.yml down --volumes
# export CID=$(sudo docker ps -aqf name=aeon_dev)
# sudo docker exec -it $CID bash
# sudo docker exec -it $CID conda-run python
version: "2.4"

services:
  aeon_dev:
    environment:
      DJ_USER: ${DJ_USER:-root}
      DJ_PASS: ${DJ_PASS:-simple}
      DJ_HOST: ${DJ_HOST:-host.docker.internal}
    image: aeon_mecha:v0.0.0dev
    build:
      context: ../../../../.
      dockerfile: ./aeon/dj_pipeline/docker/image/Dockerfile
      args:
        NEW_USER_UID: ${NEW_USER_UID:-1000}
        NEW_USER_GID: ${NEW_USER_GID:-1000}
    volumes:
      - "${LOCAL_CEPH_ROOT:-/ceph/aeon}:/ceph/aeon"
      - "${LOCAL_DJ_STORE:-~/djstore}:/home/djworker/djstore"
    extra_hosts:
      - host.docker.internal:host-gateway
    command: ["tail", "-f", "/dev/null"]
