# docker-compose -f docker/docker-compose.yml -f docker/docker-compose-test.yml up -d
# docker-compose -f docker/docker-compose.yml -f docker/docker-compose-test.yml down
# docker compose -f docker/docker-compose.yml -f docker/docker-compose-test.yml config
#
# ssh -fN -M -S ~/.ssh/controlmasters/aeon-db2 jburling@hpc-gw1 -J jburling@ssh.swc.ucl.ac.uk -L 127.0.0.1:3306:aeon-db:3306
# ssh -o ControlPath=~/.ssh/controlmasters/aeon-db2 -O check 1
# ssh -o ControlPath=~/.ssh/controlmasters/aeon-db2 -O stop 1

x-aeon-docker-test-image: &aeon-docker-test-image
  image: ${DEV_CONTAINER_IMAGE:-ghcr.io/vathes/aeon_mecha:latest}
  env_file:
    - test.env
  environment:
    DJ_USER: ${DJ_USER_TEST:-root}
    DJ_PASS: ${DJ_PASS_TEST:-simple}
    DJ_HOST: ${DJ_HOST_TEST:-host.docker.internal}

services:
  ingest_high:
    <<: *aeon-docker-test-image
    command: ["aeon_ingest", "high", "-d", "1", "-s", "1"]

  ingest_mid:
    <<: *aeon-docker-test-image
    deploy:
      replicas: 1
    command: ["aeon_ingest", "mid", "-d", "1", "-s", "1"]

  dev:
    <<: *aeon-docker-test-image
    deploy:
      replicas: 1
    volumes:
      - vscode-server:/home/aeon_db/.vscode-server/extensions

volumes:
  vscode-server:
    name: aeon-dev-vscode-server
