version: "3.9"
services:
  aeon_ingest:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        GITHUB_USER: vathes
        GITHUB_REPO: aeon_mecha
        GITHUB_BRANCH: datajoint_pipeline
        USER_NAME: datajoint
        USER_GROUP: aeon
        PROJECT_NAME: aeon
        RAW_DATA_PATH: /ceph/aeon
    image: aeon_ingest:latest
    volumes:
      # map shared folder on local host machine to USER_DATA_DIR/mnt in container
      - /Users/joseph/datajoint/projects/Aeon/mnt:/home/datajoint/aeon/mnt
      # map raw data folder on local host machine to existing directory in container
      - /Users/joseph/SSHFS/aeon/ceph/aeon:/ceph/aeon
    extra_hosts:
      - "host.docker.internal:host-gateway" # 172.17.0.1
    env_file: .env
    # command: ["python", "process.py"]
