# docker-compose -f docker/docker-compose.yml -f docker/docker-compose-test.yml up -d
# docker-compose -f docker/docker-compose.yml -f docker/docker-compose-test.yml down --volumes
# docker compose -f docker/docker-compose.yml -f docker/docker-compose-test.yml config
#
# ssh -fN -M -S ~/.ssh/controlmasters/aeon-db2 jburling@hpc-gw1 -J jburling@ssh.swc.ucl.ac.uk -L 127.0.0.1:3306:aeon-db:3306
# ssh -o ControlPath=~/.ssh/controlmasters/aeon-db2 -O check 1
# ssh -o ControlPath=~/.ssh/controlmasters/aeon-db2 -O stop 1

x-compose-env-files: &compose-env-files
  env_file:
    - test.env

services:
  ingest_high:
    <<: *compose-env-files
    scale: 1
    command: ["aeon_ingest", "high", "-d", "1", "-s", "1"]

  ingest_mid:
    <<: *compose-env-files
    scale: 1
    command: ["aeon_ingest", "mid", "-d", "1", "-s", "1"]
