# sudo docker-compose -p aeon_dev --verbose -f docker/image/docker-compose-dev.yml up --build --force-recreate --remove-orphans -d
# sudo docker-compose -p aeon_dev -f docker/image/docker-compose-dev.yml down --volumes
# export CID=$(sudo docker ps -aqf name=aeon_dev)
# sudo docker exec -it $CID bash
# sudo docker exec -it $CID conda-run python
version: "2.4"

services:
  aeon_dev:
    environment:
      DJ_USER: ${DJ_USER:-root}
      DJ_PASS: ${DJ_PASS:-simple}
      DJ_HOST: ${DJ_HOST:-host.docker.internal}
    image: aeon_mecha:v0.0.0dev
    build:
      context: ../../.
      dockerfile: docker/image/Dockerfile
      args:
        NEW_USER_UID: ${NEW_USER_UID:-6001}
        NEW_USER_GID: ${NEW_USER_GID:-6001}
    volumes:
      - "${LOCAL_CEPH_ROOT:-~/ceph/aeon}:/ceph/aeon"
      - "${LOCAL_DJ_STORE:-~/djstore}:/ceph/aeon/aeon/dj_store"
    extra_hosts:
      - host.docker.internal:host-gateway
    init: true
    # entrypoint: ["/bin/bash", "-lc"]
    # command: "tail -f /dev/null"
    # tty: true
    # user: aeon_db:aeon_db
