# Setup containers for Aeon DataJoint pipeline ingestion routines
# Joseph Burling <joseph@datajoint.com>
# --------------------------------------------------------------------------------------
# Basic usage:
#   docker-compose up --detach
#   docker-compose down
#   docker-compose down --volumes
#
# Shared properties across services ----------------------------------------------------

version: "2.4"

x-aeon-docker-image: &aeon-docker-image
  image: ghcr.io/${GITHUB_REPO_OWNER:-vathes}/aeon_mecha:latest

x-aeon-ingest-common: &aeon-ingest-common
  <<: *aeon-docker-image
  environment:
    DJ_USER: ${DJ_USER:-root}
    DJ_PASS: ${DJ_PASS:-simple}
    DJ_HOST: ${DJ_HOST:-host.docker.internal}
  volumes:
    # map raw data directory $LOCAL_CEPH_ROOT on host to $CEPH_ROOT in image
    - "${LOCAL_CEPH_ROOT:-/ceph/aeon}:/ceph/aeon"
    # map image directory $CEPH_ROOT to a container volume
    - djstore:/home/condauser/djstore
  extra_hosts:
    - host.docker.internal:host-gateway # 172.17.0.1
  scale: 1
  command: ["tail", "-f", "/dev/null"]

services:
  aeon_high:
    <<: *aeon-ingest-common
    scale: 1
    # command: ["aeon_ingest", "high", "-d", "20", "-s", "1"]

  aeon_mid:
    <<: *aeon-ingest-common
    depends_on:
      aeon_high:
        condition: service_started
    scale: 2
    # command: ["aeon_ingest", "mid", "-d", "20", "-s", "1"]

volumes:
  djstore:
    name: aeon-external-store
